apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deployment
  labels:
    app: minha-aplicacao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      containers:
      - name: minha-imagem
        image: rpolisciuc/minha-imagem:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: meu-service
spec:
  type: ClusterIP
  selector:
    app: minha-aplicacao
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: meu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /minha-aplicacao
        backend:
          serviceName: meu-service
          servicePort: 3000